SELECT TOP 200 [dimFolio_SK], 
               [dimPropertyClass_SK], 
               [Roll Year], 
               [Cycle Number], 
               SUM([Actual Land Value]) AS [Actual Land Value], 
               SUM([Actual Building Value]) AS [Actual Building Value], 
               SUM([Actual Land Value]) + SUM([Actual Building Value]) AS [Actual - Total], 
               SUM([Gross General Land Value]) AS [Gross_Gen_Land], 
               SUM([Gross General Building Value]) AS [Gross_Gen_Improvements], 
               SUM([General Exemptions Land Value]) AS [Exempt_Gen_Land], 
               SUM([General Exemptions Building Value]) AS [Exempt_Gen_Improvements], 
               SUM([Net General Land Value]) AS [Net_Gen_Land], 
               SUM([Net General Building Value]) AS [Net_Gen_Improvements], 
               SUM([Gross Other Land Value]) AS [Gross_Hosp_Land], 
               SUM([Gross Other Building Value]) AS [Gross_Hosp_Improvements], 
               SUM([Other Exemptions Land Value]) AS [Exempt_Hosp_Land], 
               SUM([Other Exemptions Building Value]) AS [Exempt_Hosp_Improvements], 
               SUM([Net Other Land Value]) AS [Net_Hosp_Land], 
               SUM([Net Other Building Value]) AS [Net_Hosp_Improvements], 
               SUM([Gross School Land Value]) AS [Gross_School_Land], 
               SUM([Gross School Building Value]) AS [Gross_School_Improvements], 
               SUM([School Exemptions Land Value]) AS [Exempt_School_Land], 
               SUM([School Exemptions Building Value]) AS [Exempt_School_Improvements], 
               SUM([Net School Land Value]) AS [Net_School_Land], 
               SUM([Net School Building Value]) AS [Net_School_Improvements]
FROM [edw].[FactTotalAllAmounts]
GROUP BY [dimFolio_SK], 
         [dimPropertyClass_SK], 
         [Roll Year], 
         [Cycle Number];


SELECT [dimFolio_SK], 
               [dimPropertyClass_SK], 
               [Roll Year], 
               [Cycle Number], 
               SUM([Actual Land Value]) AS [Actual Land Value], 
               SUM([Actual Building Value]) AS [Actual Building Value], 
               SUM([Actual Land Value]) + SUM([Actual Building Value]) AS [Actual - Total], 
               SUM([Gross General Land Value]) AS [Gross_Gen_Land], 
               SUM([Gross General Building Value]) AS [Gross_Gen_Improvements], 
               SUM([General Exemptions Land Value]) AS [Exempt_Gen_Land], 
               SUM([General Exemptions Building Value]) AS [Exempt_Gen_Improvements], 
               SUM([Net General Land Value]) AS [Net_Gen_Land], 
               SUM([Net General Building Value]) AS [Net_Gen_Improvements], 
               SUM([Gross Other Land Value]) AS [Gross_Hosp_Land], 
               SUM([Gross Other Building Value]) AS [Gross_Hosp_Improvements], 
               SUM([Other Exemptions Land Value]) AS [Exempt_Hosp_Land], 
               SUM([Other Exemptions Building Value]) AS [Exempt_Hosp_Improvements], 
               SUM([Net Other Land Value]) AS [Net_Hosp_Land], 
               SUM([Net Other Building Value]) AS [Net_Hosp_Improvements], 
               SUM([Gross School Land Value]) AS [Gross_School_Land], 
               SUM([Gross School Building Value]) AS [Gross_School_Improvements], 
               SUM([School Exemptions Land Value]) AS [Exempt_School_Land], 
               SUM([School Exemptions Building Value]) AS [Exempt_School_Improvements], 
               SUM([Net School Land Value]) AS [Net_School_Land], 
               SUM([Net School Building Value]) AS [Net_School_Improvements]
FROM [edw].[FactTotalAllAmounts]
GROUP BY [dimFolio_SK], 
         [dimPropertyClass_SK], 
         [Roll Year], 
         [Cycle Number];