select TABLE_NAME, COLUMN_NAME from [INFORMATION_SCHEMA].[COLUMNS]
WHERE COLUMN_NAME like '%Agricultural%'

--select TABLE_NAME, COLUMN_NAME from [INFORMATION_SCHEMA].[COLUMNS]
--WHERE COLUMN_NAME like '%Parcel%'

--select TABLE_NAME, COLUMN_NAME from [INFORMATION_SCHEMA].[COLUMNS]
--WHERE COLUMN_NAME like '%Tenure%'

--select TABLE_NAME, COLUMN_NAME from [INFORMATION_SCHEMA].[COLUMNS]
--WHERE COLUMN_NAME like '%Parcel%'