/*
Script Name: Resorts of the Canadian Rockies.sql
Written By: Lawrence Denvir 
Requested By: Data Services
Date Created: August 1, 2017
Last Updated:
Description: 
*/

WITH DATASET AS (
    SELECT DM.*
    FROM BCA_DM.FOLIOS DM          
    WHERE DM.AA_CODE = '22'
        AND DM.NE_CODE IN ('701041', '718505')   
        AND DM.ROLLYEAR = 2019                       

   /*No Group Care Homes*/
        AND NVL(DM.MC_CODE, ' ') <> 'C424'      
        AND NVL(DM.MC_CODE, ' ') <> 'D424'                     	
        AND NVL(DM.AU_CODE, ' ') <> '287'
        AND NVL(DM.AU_CODE, ' ') <> '040'       
        
        AND NOT EXISTS (    
            SELECT 'X'
            FROM BCA_DM.FOLIO_PC_PROFILE PCP    
            WHERE PCP.ROLLYEAR = DM.ROLLYEAR
                AND PCP.OA000_OID = DM.OA000_OID
                AND PCP.PC_03_IND = 1    
        )	    
)

SELECT 
    TO_CHAR(DM.ROLLYEAR, '0000') AS ROLLYEAR    
	,(SELECT REG.RG_NAME    
		FROM BCA_QA.BCA_QA_ASSESSMENT_REGIONS_VW REG
    	WHERE REG.ROLLYEAR = DM.ROLLYEAR
    		AND REG.NE_CODE = DM.NE_CODE) AS REGION
            
/*ASSESSMENT AREA, JURISDICTION, ROLL NUMBER*/          
    ,TO_CHAR(DM.AA_CODE, '00') AS AREA
    ,TO_CHAR(DM.JUR_CODE,'000') AS JUR
    ,TO_CHAR(DM.ROLL_NUM) AS ROLL_NUM 
	,TO_CHAR(DM.NE_CODE) AS NEIGH

/*PRIMARY ACTUAL USE CODE*/           
    ,(SELECT AR.DESCRIPTION
         FROM BCA_AO.AO_R_ACTUAL_USE AU        
            JOIN BCA_AO.AO_R_ACTUAL_USE_CATEGORY AR
                ON (AU.ROLLYEAR = AR.ROLLYEAR AND AU.ACTUAL_USE_CATEGORY=AR.CODE )
        WHERE AU.ROLLYEAR = DM.ROLLYEAR AND AU.CODE = DM.AU_CODE) AS PROPERTY_TYPE      
 
    ,(SELECT AU.CODE||' - '||AU.DESCRIPTION 
    	FROM BCA_AO.AO_R_ACTUAL_USE AU
      	WHERE AU.ROLLYEAR = DM.ROLLYEAR 
      		AND AU.CODE = DM.AU_CODE) AS PRIMARY_ACTUAL_USE

/*MANUAL CLASS CODE (MAIN BUILDING)*/    
    ,DM.MC_CODE AS PRED_MANUAL_CLASS

/*ADDRESS (INCLUDES UNIT NUMBER, STREET NUMBER AND NAME, TYPE, AND DIRECTION)*/    
    ,BCA_VDS.PKG_CEEI_CACHE.CIVIC_ADDRESS(DM.OA000_OID, DM.ROLLYEAR) AS PROPERTY_ADDRESS

/*LAND TITLE PID NUMBER (PARCEL ID)*/        
    ,DM.PID
    
/*LEGAL DESCRIPTION*/    
    ,DM.LEGAL_TEXT AS LEGAL_DESCRIPTION

/*LAND SIZE AND LAND DEPTH*/    
    ,(SELECT DT.DESCRIPTION
                FROM BCA_AO.AO_U_DIM_TYPE DT
                WHERE DM.LAND_DIM_TYPE = DT.CODE
            ) AS LAND_TYPE_NAME
    ,DM.LAND_SIZE
    ,DM.LAND_DEPTH

/*ACTUAL VALUE – TOTAL*/    
    ,DM.ACTUAL_LAND + DM.ACTUAL_IMPR AS ACTUAL_TOTAL
/*ACTUAL VALUE – LAND*/    
    ,DM.ACTUAL_LAND
/*ACTUAL VALUE – IMPROVEMENT*/
    ,DM.ACTUAL_IMPR

/*PROPERTY CLASS*/    
    ,(SELECT LISTAGG(PCS_X.PC_CODE, '/ ') WITHIN GROUP (ORDER BY 1)
        FROM (
            SELECT DISTINCT
                PCS.ROLLYEAR
                ,PCS.OA000_OID
                ,PCS.PC_CODE                
            FROM BCA_DM.FOLIOS_PCS PCS
        ) PCS_X    
        WHERE PCS_X.OA000_OID = DM.OA000_OID 
            AND PCS_X.ROLLYEAR = DM.ROLLYEAR) AS PROPERTY_CLASS    

/*REGIONAL DISTRICT*/    
    ,(SELECT RD.CODE || ' - ' || DESCRIPTION 
    	FROM BCA_AO.AO_R_REGIONAL_DISTRICT RD
        WHERE RD.ROLLYEAR = DM.ROLLYEAR 
        AND RD.CODE = DM.RD_CODE) AS REGIONAL_DISTRICT

/*BUILDING COUNT*/
 ,(NVL((SELECT COUNT(DISTINCT OJ.OJ000_OID)                
        FROM BCA_AO.OJ000_MAIN_BLDG OJ    	
        WHERE NVL(OJ.SUPPRESS,'F') = 'F'
            AND OJ.OA000_OID = DM.OA000_OID
            AND OJ.ROLLYEAR = DM.ROLLYEAR),0) +            
            NVL((SELECT COUNT( DISTINCT JA.JA000_OID)                
                FROM BCA_AO.LINK_JA000_OA000 JAOA
                    JOIN BCA_AO.JA000_COMBUILDING JA
                        ON (JA.ROLLYEAR = JAOA.ROLLYEAR AND JA.JA000_OID = JAOA.JA000_OID)    	
                WHERE JAOA.OA000_OID = DM.OA000_OID
                    AND JAOA.ROLLYEAR = DM.ROLLYEAR),0)                    
        ) AS BLDG_COUNT      	

/*BUILDING TYPE*/   
   ,CASE WHEN NVL(DM.VACANT_FLAG, 'F') = 'T' THEN  'Vacant' 
            ELSE 'Non-Vacant-Other'
    END AS BUILDING_TYPE
    ,NULL AS BUILDING_ID

/*YEAR BUILT*/
    ,NULL AS YEAR_BUILT    
/*TOTAL FINISHED AREA*/
	,NULL AS TOTAL_FINISHED_AREA
/*NUMBER OF BATHROOMS*/                                                       
	,NULL AS NUMBER_OF_BATHROOMS
/*NUMBER OF BEDROOMS*/
    ,NULL AS NUMBER_OF_BEDROOMS  
/*STRATA UNIT AREA*/
	,NULL AS STRATA_UNIT_AREA  
/*PREDOMINANT_OCCUPANCY*/
    ,NULL AS PREDOMINANT_OCCUPANCY
/*NUMBER_OF_STOREYS*/
    ,NULL AS NUMBER_OF_STOREYS

/*GROSS_BUILDING_AREA*/ 
    ,NULL AS GROSS_BUILDING_AREA    
    ,NULL AS GROSS_LEASABLE_AREA
	,NULL AS NET_LEASABLE_AREA    
                                     
FROM DATASET DM          

/*No Unsuppressed main buildings*/	
WHERE NOT EXISTS (
    	SELECT 'X' FROM BCA_AO.OJ000_MAIN_BLDG OJX
       	WHERE  OJX.ROLLYEAR = DM.ROLLYEAR
        	AND OJX.OA000_OID = DM.OA000_OID
            AND NVL(OJX.SUPPRESS,'F')='F')
/*No linked combuildings*/            
 	AND NOT EXISTS (
    	SELECT 'X' FROM BCA_AO.LINK_JA000_OA000 JAOA
    	WHERE JAOA.ROLLYEAR = DM.ROLLYEAR
        	AND JAOA.OA000_OID = DM.OA000_OID)     
          
UNION ALL

SELECT 
    TO_CHAR(DM.ROLLYEAR, '0000') AS ROLLYEAR    
	,(SELECT REG.RG_NAME    
		FROM BCA_QA.BCA_QA_ASSESSMENT_REGIONS_VW REG
    	WHERE REG.ROLLYEAR = DM.ROLLYEAR
    		AND REG.NE_CODE = DM.NE_CODE) AS REGION  
            
/*ASSESSMENT AREA, JURISDICTION, ROLL NUMBER*/          
    ,TO_CHAR(DM.AA_CODE) AS AREA
    ,TO_CHAR(DM.JUR_CODE) AS JUR
    ,TO_CHAR(DM.ROLL_NUM) AS ROLL_NUM 
    
    ,TO_CHAR(DM.NE_CODE) AS NEIGH

/*PRIMARY ACTUAL USE CODE*/           
    ,(SELECT AR.DESCRIPTION
         FROM BCA_AO.AO_R_ACTUAL_USE AU        
            JOIN BCA_AO.AO_R_ACTUAL_USE_CATEGORY AR
                ON (AU.ROLLYEAR = AR.ROLLYEAR AND AU.ACTUAL_USE_CATEGORY=AR.CODE )
        WHERE AU.ROLLYEAR = DM.ROLLYEAR AND AU.CODE = DM.AU_CODE) AS PROPERTY_TYPE      
 
    ,(SELECT AU.CODE||' - '||AU.DESCRIPTION 
    	FROM BCA_AO.AO_R_ACTUAL_USE AU
      	WHERE AU.ROLLYEAR = DM.ROLLYEAR 
      		AND AU.CODE = DM.AU_CODE) AS PRIMARY_ACTUAL_USE

/*MANUAL CLASS CODE (MAIN BUILDING)*/    
    ,DM.MC_CODE AS PRED_MANUAL_CLASS

/*ADDRESS (INCLUDES UNIT NUMBER, STREET NUMBER AND NAME, TYPE, AND DIRECTION)*/    
    ,BCA_VDS.PKG_CEEI_CACHE.CIVIC_ADDRESS(DM.OA000_OID, DM.ROLLYEAR) AS PROPERTY_ADDRESS

/*LAND TITLE PID NUMBER (PARCEL ID)*/        
    ,DM.PID
    
/*LEGAL DESCRIPTION*/    
    ,DM.LEGAL_TEXT AS LEGAL_DESCRIPTION
    
/*LAND SIZE AND LAND DEPTH*/    
    ,(SELECT DT.DESCRIPTION
                FROM BCA_AO.AO_U_DIM_TYPE DT
                WHERE DM.LAND_DIM_TYPE = DT.CODE
            ) AS LAND_TYPE_NAME
    ,DM.LAND_SIZE
    ,DM.LAND_DEPTH

/*ACTUAL VALUE – TOTAL*/    
    ,DM.ACTUAL_LAND + DM.ACTUAL_IMPR AS ACTUAL_TOTAL
/*ACTUAL VALUE – LAND*/    
    ,DM.ACTUAL_LAND
/*ACTUAL VALUE – IMPROVEMENT*/
    ,DM.ACTUAL_IMPR

/*PROPERTY CLASS*/    
    ,(SELECT LISTAGG(PCS_X.PC_CODE, '/ ') WITHIN GROUP (ORDER BY 1)
        FROM (
            SELECT DISTINCT
                PCS.ROLLYEAR
                ,PCS.OA000_OID
                ,PCS.PC_CODE                
            FROM BCA_DM.FOLIOS_PCS PCS
        ) PCS_X    
        WHERE PCS_X.OA000_OID = DM.OA000_OID 
            AND PCS_X.ROLLYEAR = DM.ROLLYEAR) AS PROPERTY_CLASS    

/*REGIONAL DISTRICT*/    
    ,(SELECT RD.CODE || ' - ' || DESCRIPTION 
    	FROM BCA_AO.AO_R_REGIONAL_DISTRICT RD
        WHERE RD.ROLLYEAR = DM.ROLLYEAR 
        AND RD.CODE = DM.RD_CODE) AS REGIONAL_DISTRICT

/*BUILDING COUNT*/
  ,(NVL((SELECT COUNT(DISTINCT OJ.OJ000_OID)                
        FROM BCA_AO.OJ000_MAIN_BLDG OJ    	
        WHERE NVL(OJ.SUPPRESS,'F') = 'F'
            AND OJ.OA000_OID = DM.OA000_OID
            AND OJ.ROLLYEAR = DM.ROLLYEAR),0) +            
            NVL((SELECT COUNT( DISTINCT JA.JA000_OID)                
                FROM BCA_AO.LINK_JA000_OA000 JAOA
                    JOIN BCA_AO.JA000_COMBUILDING JA
                        ON (JA.ROLLYEAR = JAOA.ROLLYEAR AND JA.JA000_OID = JAOA.JA000_OID)    	
                WHERE JAOA.OA000_OID = DM.OA000_OID
                    AND JAOA.ROLLYEAR = DM.ROLLYEAR),0)                    
        ) AS BLDG_COUNT      	
  
/*BUILDING TYPE*/
     ,(CASE OJ.BUILDING_TYPE
            WHEN '1' THEN 'SFD'    
            WHEN '2' THEN 'MFH'
            END) AS BUILDING_TYPE
	,TO_CHAR(OJ.BUILDING_ID) AS BUILDING_ID   

/*YEAR BUILT*/
    ,TO_CHAR(NVL(OJ.YEAR_BUILT, OJ.MH_YEAR_BUILT)) AS YEAR_BUILT
    
/*TOTAL FINISHED AREA*/
    ,(CASE OJ.BUILDING_TYPE 
           WHEN '1' THEN OJ.TOTAL_AREA
           WHEN '2' THEN OJ.MH_AREA            
      END) AS TOTAL_FINISHED_AREA 
      
/*NUMBER OF BATHROOMS*/
/*need to replace with counts from res attributes*/                                                       
	,(SELECT SUM(NVL(OJC.FBATH_1, 0) + NVL(OJC.FBATH_2, 0) + NVL(OJC.FBATH_3, 0) + NVL(OJC.FBATH_A, 0) + NVL(OJC.FBATH_B, 0)
               + NVL(OJC.PBATH_1, 0) + NVL(OJC.PBATH_2, 0) + NVL(OJC.PBATH_3, 0) + NVL(OJC.PBATH_A, 0) + NVL(OJC.PBATH_B, 0))		
        FROM BCA_AO.OJC00_ACCOMMODATION OJC
          WHERE OJC.ROLLYEAR = OJ.ROLLYEAR 
          AND OJC.OJ000_OID = OJ.OJ000_OID) AS NUMBER_OF_BATHROOMS
/*NUMBER OF BEDROOMS*/
    ,ROUND((SELECT SUM(NVL(OJC.BEDROOM_1, 0) + NVL(OJC.BEDROOM_2, 0) + NVL(OJC.BEDROOM_3, 0) + NVL(OJC.BEDROOM_A, 0) + NVL(OJC.BEDROOM_B, 0))		
        FROM BCA_AO.OJC00_ACCOMMODATION OJC
          WHERE OJC.ROLLYEAR = OJ.ROLLYEAR 
          AND OJC.OJ000_OID = OJ.OJ000_OID),0) AS NUMBER_OF_BEDROOMS 

/*STRATA UNIT AREA*/
 	,NULL AS STRATA_UNIT_AREA             
/*OCCUPANCY*/
	,NULL AS PREDOMINANT_OCCUPANCY
    
/*NUMBER OF STOREYS*/
    ,TO_CHAR(CASE 
        WHEN OJ.THIRD_FLOOR_AREA IS NOT NULL THEN 3 
        WHEN OJ.SECOND_FLOOR_AREA IS NOT NULL THEN 2 
        WHEN OJ.HALF_STOREY_AREA IS NOT NULL THEN 1.5 
        WHEN OJ.FIRST_FLOOR_AREA IS NOT NULL THEN 1 
        ELSE NVL((SELECT MC.STORIES
                FROM BCA_AO.AO_R_MANUAL_CLASS MC
                WHERE MC.ROLLYEAR = OJ.ROLLYEAR
                    AND MC.CODE = NVL(OJ.MANUAL_CLASS, OJ.MH_MANUAL_CLASS)),0)
    END) AS NUMBER_OF_STOREYS             
	
/*GROSS_BUILDING_AREA*/
    ,NULL AS GROSS_BUILDING_AREA
    ,NULL AS GROSS_LEASABLE_AREA
    ,NULL AS NET_LEASABLE_AREA       
                       
FROM DATASET DM          
	JOIN BCA_AO.OJ000_MAIN_BLDG OJ    
    	ON (OJ.ROLLYEAR = DM.ROLLYEAR AND OJ.OA000_OID = DM.OA000_OID AND NVL(OJ.SUPPRESS,'F') = 'F')

UNION ALL

SELECT 
    TO_CHAR(DM.ROLLYEAR, '0000') AS ROLLYEAR    
	,(SELECT REG.RG_NAME    
		FROM BCA_QA.BCA_QA_ASSESSMENT_REGIONS_VW REG
    	WHERE REG.ROLLYEAR = DM.ROLLYEAR
    		AND REG.NE_CODE = DM.NE_CODE) AS REGION
            
/*ASSESSMENT AREA, JURISDICTION, ROLL NUMBER*/          
    ,TO_CHAR(DM.AA_CODE) AS AREA
    ,TO_CHAR(DM.JUR_CODE) AS JUR
    ,TO_CHAR(DM.ROLL_NUM) AS ROLL_NUM 
    ,TO_CHAR(DM.NE_CODE) AS NEIGH

/*PRIMARY ACTUAL USE CODE*/           
    ,(SELECT AR.DESCRIPTION
         FROM BCA_AO.AO_R_ACTUAL_USE AU        
            JOIN BCA_AO.AO_R_ACTUAL_USE_CATEGORY AR
                ON (AU.ROLLYEAR = AR.ROLLYEAR AND AU.ACTUAL_USE_CATEGORY=AR.CODE )
        WHERE AU.ROLLYEAR = DM.ROLLYEAR AND AU.CODE = DM.AU_CODE) AS PROPERTY_TYPE      
 
    ,(SELECT AU.CODE||' - '||AU.DESCRIPTION 
    	FROM BCA_AO.AO_R_ACTUAL_USE AU
      	WHERE AU.ROLLYEAR = DM.ROLLYEAR 
      		AND AU.CODE = DM.AU_CODE) AS PRIMARY_ACTUAL_USE    

/*MANUAL CLASS CODE (MAIN BUILDING)*/    
    ,DM.MC_CODE AS PRED_MANUAL_CLASS /*Code or description*/

/*ADDRESS (INCLUDES UNIT NUMBER, STREET NUMBER AND NAME, TYPE, AND DIRECTION)*/    
    ,BCA_VDS.PKG_CEEI_CACHE.CIVIC_ADDRESS(DM.OA000_OID, DM.ROLLYEAR) AS PROPERTY_ADDRESS

/*LAND TITLE PID NUMBER (PARCEL ID)*/        
    ,DM.PID
    
/*LEGAL DESCRIPTION*/    
    ,DM.LEGAL_TEXT AS LEGAL_DESCRIPTION
    
/*LAND SIZE AND LAND DEPTH*/    
    ,(SELECT DT.DESCRIPTION
                FROM BCA_AO.AO_U_DIM_TYPE DT
                WHERE DM.LAND_DIM_TYPE = DT.CODE
            ) AS LAND_TYPE_NAME
    ,DM.LAND_SIZE
    ,DM.LAND_DEPTH

/*ACTUAL VALUE – TOTAL*/    
    ,DM.ACTUAL_LAND + DM.ACTUAL_IMPR AS ACTUAL_TOTAL
/*ACTUAL VALUE – LAND*/    
    ,DM.ACTUAL_LAND
/*ACTUAL VALUE – IMPROVEMENT*/
    ,DM.ACTUAL_IMPR

/*PROPERTY CLASS*/    
    ,(SELECT LISTAGG(PCS_X.PC_CODE, '/ ') WITHIN GROUP (ORDER BY 1)
        FROM (
            SELECT DISTINCT
                PCS.ROLLYEAR
                ,PCS.OA000_OID
                ,PCS.PC_CODE                
            FROM BCA_DM.FOLIOS_PCS PCS
        ) PCS_X    
        WHERE PCS_X.OA000_OID = DM.OA000_OID 
            AND PCS_X.ROLLYEAR = DM.ROLLYEAR) AS PROPERTY_CLASS    

/*REGIONAL DISTRICT*/    
    ,(SELECT RD.CODE || ' - ' || DESCRIPTION 
    	FROM BCA_AO.AO_R_REGIONAL_DISTRICT RD
        WHERE RD.ROLLYEAR = DM.ROLLYEAR 
        AND RD.CODE = DM.RD_CODE) AS REGIONAL_DISTRICT

/*BUILDING COUNT*/
  ,(NVL((SELECT COUNT(DISTINCT OJ.OJ000_OID)                
        FROM BCA_AO.OJ000_MAIN_BLDG OJ    	
        WHERE NVL(OJ.SUPPRESS,'F') = 'F'
            AND OJ.OA000_OID = DM.OA000_OID
            AND OJ.ROLLYEAR = DM.ROLLYEAR),0) +            
            NVL((SELECT COUNT( DISTINCT JA.JA000_OID)                
                FROM BCA_AO.LINK_JA000_OA000 JAOA
                    JOIN BCA_AO.JA000_COMBUILDING JA
                        ON (JA.ROLLYEAR = JAOA.ROLLYEAR AND JA.JA000_OID = JAOA.JA000_OID)    	
                WHERE JAOA.OA000_OID = DM.OA000_OID
                    AND JAOA.ROLLYEAR = DM.ROLLYEAR),0)                    
        ) AS BLDG_COUNT      	

/*BUILDING TYPE*/
    ,(SELECT IMT.DESCRIPTION    
        FROM BCA_AO.AO_L_INCOME_MODEL_TYPE IMT                
        WHERE IMT.CODE = JA.BUILDING_TYPE) AS BUILDING_TYPE 

    ,TO_CHAR(JA.BUILDING_ID) AS BUILDING_ID
    
/*YEAR BUILT*/
    ,TO_CHAR(JA.YEAR_BUILT) AS YEAR_BUILT 
    
/*TOTAL FINISHED AREA*/
	,NULL AS TOTAL_FINISHED_AREA                 

/*NUMBER OF BATHROOMS*/                                                       
    ,(SELECT SUM(IBA.VALUE)	
    	FROM BCA_AO.LINK_JA000_IA000 JAIA
        	JOIN BCA_AO.IA000_INCOME IA
            	ON (IA.ROLLYEAR = JAIA.ROLLYEAR AND IA.IA000_OID = JAIA.IA000_OID AND NVL(IA.SUPPRESS,'F') = 'F')
			JOIN BCA_AO.IB000_OCCUPANCY IB
            	ON (IB.ROLLYEAR = IA.ROLLYEAR AND IB.IA000_OID = IA.IA000_OID)              
			JOIN BCA_AO.IBA00_ATTR_AND_ADJ IBA
            	ON (IBA.ROLLYEAR = IB.ROLLYEAR AND IBA.IB000_OID = IB.IB000_OID)     
			JOIN BCA_AO.AO_R_INCOME_ATTRIBUTE INCATTR  
            	ON (INCATTR.ROLLYEAR = IBA.ROLLYEAR AND INCATTR.CODE = IBA.ATTRIBUTE)                     	                
		WHERE JAIA.ROLLYEAR = JA.ROLLYEAR
        	AND JAIA.JA000_OID = JA.JA000_OID
            AND INCATTR.MASK_ID <> 'YN'
            AND INCATTR.MASK_TYPE <> 'LIST'
            AND UPPER(INCATTR.DESCRIPTION) LIKE '%BATH%'
            AND IBA.ATTRIBUTE IN (            
                'FBATHSR' /* Bath Full Number of-STR*/
                ,'HBATHSR' /* Bath 1/2 Number of-STR*/
                ,'PLBATHSR' /* Bath Plus Number of-STR*/
                ,'TQBATHSR' /* Bath 3/4 Number of-STR*/
            )            
	) AS NUMBER_OF_BATHROOMS
              
/*NUMBER OF BEDROOMS*/
    ,ROUND((NVL((SELECT SUM(TO_NUMBER(IBA.VALUE))	
    	FROM BCA_AO.LINK_JA000_IA000 JAIA
        	JOIN BCA_AO.IA000_INCOME IA
            	ON (IA.ROLLYEAR = JAIA.ROLLYEAR AND IA.IA000_OID = JAIA.IA000_OID AND NVL(IA.SUPPRESS,'F') = 'F')
			JOIN BCA_AO.IB000_OCCUPANCY IB
            	ON (IB.ROLLYEAR = IA.ROLLYEAR AND IB.IA000_OID = IA.IA000_OID)              
			JOIN BCA_AO.IBA00_ATTR_AND_ADJ IBA
            	ON (IBA.ROLLYEAR = IB.ROLLYEAR AND IBA.IB000_OID = IB.IB000_OID)     
			JOIN BCA_AO.AO_R_INCOME_ATTRIBUTE INCATTR  
            	ON (INCATTR.ROLLYEAR = IBA.ROLLYEAR AND INCATTR.CODE = IBA.ATTRIBUTE)                     	                
		WHERE JAIA.ROLLYEAR = JA.ROLLYEAR
        	AND JAIA.JA000_OID = JA.JA000_OID
            AND INCATTR.MASK_ID <> 'YN'
            AND INCATTR.MASK_TYPE <> 'LIST'            
            AND UPPER(INCATTR.DESCRIPTION) LIKE '%BEDROOMS%'),0)        +     
    NVL((SELECT SUM(NVL(IB.NUM_UNITS,0)*TO_NUMBER(SUBSTR(IB.UNIT_OF_MEASURE,4,1)))
        FROM BCA_AO.LINK_JA000_IA000 JAIA
        	JOIN BCA_AO.IA000_INCOME IA
            	ON (IA.ROLLYEAR = JAIA.ROLLYEAR AND IA.IA000_OID = JAIA.IA000_OID AND NVL(IA.SUPPRESS,'F') = 'F')
			JOIN BCA_AO.IB000_OCCUPANCY IB
            	ON (IB.ROLLYEAR = IA.ROLLYEAR AND IB.IA000_OID = IA.IA000_OID)   			                                       	                
		WHERE JAIA.ROLLYEAR = JA.ROLLYEAR
        	AND JAIA.JA000_OID = JA.JA000_OID           
            AND SUBSTR(IB.UNIT_OF_MEASURE,4,1) IN ('1', '2', '3', '4')
            AND IB.UNIT_OF_MEASURE NOT LIKE '%COP%'                                     
            ),0)                         
             ),0) AS NUMBER_OF_BEDROOMS  

/*STRATA UNIT AREA*/
    ,(SELECT SUM(IB.NUM_UNITS)
        FROM BCA_AO.LINK_JA000_IA000 JAIA                                     
            JOIN BCA_AO.IA000_INCOME IA                                                     
                ON (JAIA.ROLLYEAR = IA.ROLLYEAR AND JAIA.IA000_OID = IA.IA000_OID AND NVL(IA.SUPPRESS,'F') = 'F')
            JOIN BCA_AO.IB000_OCCUPANCY IB
                ON (IA.ROLLYEAR = IB.ROLLYEAR AND IA.IA000_OID = IB.IA000_OID)
            JOIN BCA_AO.AO_L_INCOME_UNIT_MEASURE IBM
                ON (IB.UNIT_OF_MEASURE = IBM.CODE 
                	AND IBM.CODE IN ('SICLA', 'STRLA'))           
        WHERE JAIA.ROLLYEAR=JA.ROLLYEAR               
            AND JAIA.JA000_OID = JA.JA000_OID) AS STRATA_UNIT_AREA
              
/*OCCUPANCY*/
    ,(SELECT OCC1.DESCRIPTION
    	FROM BCA_AO.AO_MC_OCCUPANCYGENERAL_VIEW OCC1
        WHERE OCC1.CODE = JA.PREDOMINANT_OCCUPANCY) AS PREDOMINANT_OCCUPANCY

/*NUMBER OF STORIES*/   
    ,(SELECT TO_CHAR(MAX(JCX.NBR_STORIES_BUILDING))
        FROM BCA_AO.LINK_OA000_OA000 OAOA
            JOIN BCA_AO.OA000_PROPERTY OA_CORP
                ON (OA_CORP.ROLLYEAR = OAOA.ROLLYEAR AND OAOA.OA000_OID_FROM = OA_CORP.OA000_OID) 
            JOIN BCA_AO.LINK_JA000_OA000 JAOAX
                ON (OA_CORP.ROLLYEAR = JAOAX.ROLLYEAR AND JAOAX.OA000_OID = OA_CORP.OA000_OID)
            JOIN BCA_AO.JA000_COMBUILDING JAX
                ON (JAOAX.JA000_OID = JAX.JA000_OID AND JAOAX.ROLLYEAR = JAX.ROLLYEAR)     
            JOIN  BCA_AO.JC000_SECTION JCX
                ON (JCX.JA000_OID = JAX.JA000_OID AND JCX.ROLLYEAR = JAX.ROLLYEAR AND NVL(JCX.SUPPRESS, 'F') = 'F')                      
            WHERE OAOA.ROLLYEAR = DM.ROLLYEAR 
                AND OAOA.OA000_OID_TO = DM.OA000_OID
                AND OAOA.OA000_OA000_LINK_ROLE = '08'
                AND OA_CORP.FOLIO_STATUS = '07'
        ) AS NUMBER_OF_STOREYS        
              
/*GROSS BUILDING AREA*/  
    ,(SELECT SUM(JCX.OVERRIDE_AREA)
        FROM BCA_AO.LINK_OA000_OA000 OAOA
            JOIN BCA_AO.OA000_PROPERTY OA_CORP
                ON (OA_CORP.ROLLYEAR = OAOA.ROLLYEAR AND OAOA.OA000_OID_FROM = OA_CORP.OA000_OID) 
            JOIN BCA_AO.LINK_JA000_OA000 JAOAX
                ON (OA_CORP.ROLLYEAR = JAOAX.ROLLYEAR AND JAOAX.OA000_OID = OA_CORP.OA000_OID)
            JOIN BCA_AO.JA000_COMBUILDING JAX
                ON (JAOAX.JA000_OID = JAX.JA000_OID AND JAOAX.ROLLYEAR = JAX.ROLLYEAR)     
            JOIN  BCA_AO.JC000_SECTION JCX
                ON (JCX.JA000_OID = JAX.JA000_OID AND JCX.ROLLYEAR = JAX.ROLLYEAR AND NVL(JCX.SUPPRESS, 'F') = 'F')                      
            WHERE OAOA.ROLLYEAR = DM.ROLLYEAR 
                AND OAOA.OA000_OID_TO = DM.OA000_OID
                AND OAOA.OA000_OA000_LINK_ROLE = '08'
                AND OA_CORP.FOLIO_STATUS = '07'
        ) AS GROSS_BUILDING_AREA   
  
/*GROSS_LEASABLE_AREA*/
    ,NVL((SELECT SUM(NVL(IB.NUM_UNITS, 0))         
        FROM BCA_AO.LINK_JA000_IA000 JAIA
            JOIN BCA_AO.IA000_INCOME IA
                ON (IA.ROLLYEAR = JAIA.ROLLYEAR AND IA.IA000_OID = JAIA.IA000_OID AND NVL(IA.SUPPRESS,'F') = 'F')
            JOIN BCA_AO.IB000_OCCUPANCY IB
                ON (IB.ROLLYEAR = IA.ROLLYEAR AND IB.IA000_OID = IA.IA000_OID)   
            JOIN BCA_AO.AO_L_INCOME_UNIT_MEASURE UM
                ON (IB.UNIT_OF_MEASURE = UM.CODE) 
        WHERE  JAIA.ROLLYEAR = JA.ROLLYEAR
            AND JAIA.JA000_OID = JA.JA000_OID
            AND UM.DESCRIPTION like '%GLA%'),0) AS GROSS_LEASABLE_AREA
/*NET_LEASABLE_AREA*/
    ,NVL((SELECT SUM(NVL(IB.NUM_UNITS, 0))         
        FROM BCA_AO.LINK_JA000_IA000 JAIA
            JOIN BCA_AO.IA000_INCOME IA
                ON (IA.ROLLYEAR = JAIA.ROLLYEAR AND IA.IA000_OID = JAIA.IA000_OID AND NVL(IA.SUPPRESS,'F') = 'F')
            JOIN BCA_AO.IB000_OCCUPANCY IB
                ON (IB.ROLLYEAR = IA.ROLLYEAR AND IB.IA000_OID = IA.IA000_OID)   
            JOIN BCA_AO.AO_L_INCOME_UNIT_MEASURE UM
                ON (IB.UNIT_OF_MEASURE = UM.CODE) 
        WHERE  JAIA.ROLLYEAR = JA.ROLLYEAR
            AND JAIA.JA000_OID = JA.JA000_OID
            AND UM.DESCRIPTION like '%NLA%'),0) AS NET_LEASABLE_AREA        
                          
FROM DATASET DM          
	JOIN BCA_AO.LINK_JA000_OA000 JAOA
    	ON (JAOA.ROLLYEAR = DM.ROLLYEAR AND JAOA.OA000_OID = DM.OA000_OID)
    JOIN BCA_AO.JA000_COMBUILDING JA
    	ON (JA.ROLLYEAR = JAOA.ROLLYEAR AND JA.JA000_OID = JAOA.JA000_OID)   
    	
WHERE EXISTS  (
        SELECT 'X'
        FROM BCA_AO.OA000_PROPERTY OA
        WHERE OA.ROLLYEAR = DM.ROLLYEAR
            AND OA.OA000_OID = DM.OA000_OID
            AND OA.VALUE_METHOD_CALC <> 'CST' /*Income or DCA*/           
	)        

UNION ALL

SELECT 
    TO_CHAR(DM.ROLLYEAR, '0000') AS ROLLYEAR    
	,(SELECT REG.RG_NAME    
		FROM BCA_QA.BCA_QA_ASSESSMENT_REGIONS_VW REG
    	WHERE REG.ROLLYEAR = DM.ROLLYEAR
    		AND REG.NE_CODE = DM.NE_CODE) AS REGION 
            
/*ASSESSMENT AREA, JURISDICTION, ROLL NUMBER*/          
    ,TO_CHAR(DM.AA_CODE) AS AREA
    ,TO_CHAR(DM.JUR_CODE,'000') AS JUR
    ,TO_CHAR(DM.ROLL_NUM) AS ROLL_NUM 

	,TO_CHAR(DM.NE_CODE) AS NEIGH

/*PRIMARY ACTUAL USE CODE*/           
    ,(SELECT AR.DESCRIPTION
         FROM BCA_AO.AO_R_ACTUAL_USE AU        
            JOIN BCA_AO.AO_R_ACTUAL_USE_CATEGORY AR
                ON (AU.ROLLYEAR = AR.ROLLYEAR AND AU.ACTUAL_USE_CATEGORY=AR.CODE )
        WHERE AU.ROLLYEAR = DM.ROLLYEAR AND AU.CODE = DM.AU_CODE) AS PROPERTY_TYPE      
 
    ,(SELECT AU.CODE||' - '||AU.DESCRIPTION 
    	FROM BCA_AO.AO_R_ACTUAL_USE AU
      	WHERE AU.ROLLYEAR = DM.ROLLYEAR 
      		AND AU.CODE = DM.AU_CODE) AS PRIMARY_ACTUAL_USE

/*MANUAL CLASS CODE (MAIN BUILDING)*/    
    ,DM.MC_CODE AS PRED_MANUAL_CLASS

/*ADDRESS (INCLUDES UNIT NUMBER, STREET NUMBER AND NAME, TYPE, AND DIRECTION)*/    
    ,BCA_VDS.PKG_CEEI_CACHE.CIVIC_ADDRESS(DM.OA000_OID, DM.ROLLYEAR) AS PROPERTY_ADDRESS

/*LAND TITLE PID NUMBER (PARCEL ID)*/        
    ,DM.PID
    
/*LEGAL DESCRIPTION*/    
    ,DM.LEGAL_TEXT AS LEGAL_DESCRIPTION
    
/*LAND SIZE AND LAND DEPTH*/    
    ,(SELECT DT.DESCRIPTION
                FROM BCA_AO.AO_U_DIM_TYPE DT
                WHERE DM.LAND_DIM_TYPE = DT.CODE
            ) AS LAND_TYPE_NAME
    ,DM.LAND_SIZE
    ,DM.LAND_DEPTH

/*ACTUAL VALUE – TOTAL*/    
    ,DM.ACTUAL_LAND + DM.ACTUAL_IMPR AS ACTUAL_TOTAL
/*ACTUAL VALUE – LAND*/    
    ,DM.ACTUAL_LAND
/*ACTUAL VALUE – IMPROVEMENT*/
    ,DM.ACTUAL_IMPR

/*PROPERTY CLASS*/    
    ,(SELECT LISTAGG(PCS_X.PC_CODE, '/ ') WITHIN GROUP (ORDER BY 1)
        FROM (
            SELECT DISTINCT
                PCS.ROLLYEAR
                ,PCS.OA000_OID
                ,PCS.PC_CODE                
            FROM BCA_DM.FOLIOS_PCS PCS
        ) PCS_X    
        WHERE PCS_X.OA000_OID = DM.OA000_OID 
            AND PCS_X.ROLLYEAR = DM.ROLLYEAR) AS PROPERTY_CLASS    

/*REGIONAL DISTRICT*/    
    ,(SELECT RD.CODE || ' - ' || DESCRIPTION 
    	FROM BCA_AO.AO_R_REGIONAL_DISTRICT RD
        WHERE RD.ROLLYEAR = DM.ROLLYEAR 
        AND RD.CODE = DM.RD_CODE) AS REGIONAL_DISTRICT

/*BUILDING COUNT*/
  ,(NVL((SELECT COUNT(DISTINCT OJ.OJ000_OID)                
        FROM BCA_AO.OJ000_MAIN_BLDG OJ    	
        WHERE NVL(OJ.SUPPRESS,'F') = 'F'
            AND OJ.OA000_OID = DM.OA000_OID
            AND OJ.ROLLYEAR = DM.ROLLYEAR),0) +            
            NVL((SELECT COUNT( DISTINCT JA.JA000_OID)                
                FROM BCA_AO.LINK_JA000_OA000 JAOA
                    JOIN BCA_AO.JA000_COMBUILDING JA
                        ON (JA.ROLLYEAR = JAOA.ROLLYEAR AND JA.JA000_OID = JAOA.JA000_OID)    	
                WHERE JAOA.OA000_OID = DM.OA000_OID
                    AND JAOA.ROLLYEAR = DM.ROLLYEAR),0)                    
        ) AS BLDG_COUNT      	

/*BUILDING TYPE*/
    ,(SELECT IMT.DESCRIPTION    
        FROM BCA_AO.AO_L_INCOME_MODEL_TYPE IMT                
        WHERE IMT.CODE = JA.BUILDING_TYPE) AS BUILDING_TYPE 

    ,TO_CHAR(JA.BUILDING_ID) AS BUILDING_ID
    
/*YEAR BUILT*/
    ,TO_CHAR(JA.YEAR_BUILT) AS YEAR_BUILT 
      
/*TOTAL FINISHED AREA*/
	,NULL AS TOTAL_FINISHED_AREA                        
/*NUMBER OF BATHROOMS*/                                                       
    ,NULL AS NUMBER_OF_BATHROOMS          
/*NUMBER OF BEDROOMS*/
    ,NULL AS NUMBER_OF_BEDROOMS   

/*STRATA UNIT AREA*/
	,NULL AS STRATA_UNIT_AREA    
              
/*OCCUPANCY*/
    ,(SELECT OCC1.DESCRIPTION
    	FROM BCA_AO.AO_MC_OCCUPANCYGENERAL_VIEW OCC1
        WHERE OCC1.CODE = JA.PREDOMINANT_OCCUPANCY
	) AS PREDOMINANT_OCCUPANCY

/*NUMBER OF STORIES*/
    ,(SELECT TO_CHAR(MAX(JC.NBR_STORIES_BUILDING ))
        FROM BCA_AO.JC000_SECTION JC        		        
        WHERE JA.JA000_OID = JC.JA000_OID
            AND JA.ROLLYEAR = JC.ROLLYEAR        
            AND NVL(JC.SUPPRESS, 'F') = 'F') AS NUMBER_OF_STOREYS  

/*GROSS BUILDING AREA*/
    ,NVL((SELECT SUM(NVL(JDB.OVERRIDE_SKETCH_AREA, JDB.SKETCH_AREA))             
    FROM BCA_AO.JD000_BASEMENT JD
    JOIN BCA_AO.JDB00_OCCUPANCY JDB
        ON (JDB.ROLLYEAR = JD.ROLLYEAR AND JDB.JD000_OID = JD.JD000_OID AND NVL(JDB.SUPPRESS, 'F') = 'F')
    WHERE JD.ROLLYEAR = JA.ROLLYEAR 
        AND JD.JA000_OID = JA.JA000_OID 
        AND NVL(JD.SUPPRESS, 'F') = 'F'        
        AND JDB.OCCUPANCY_NUM NOT IN 
('556','740','745','790','791','797','805','810','850','851','900','901','902','903','904','905','910','920','921','922','923','924','925','926','927','928','930','931','999','1814','1818','1820')                                                              
--                    ('900','901','902','903','904','905','910','920','921','922','923','924','925','926','927','928','930','931','810') /*LANDCOR COM EXTRACT*/                   
        ),0) +        
   	NVL((SELECT SUM(NVL(JC.OVERRIDE_AREA, JC.SKETCH_AREA))            
    FROM BCA_AO.JC000_SECTION JC
    JOIN BCA_AO.JCC00_OCCUPANCY JCC
        ON (JCC.ROLLYEAR = JC.ROLLYEAR AND JCC.JC000_OID = JC.JC000_OID AND NVL(JCC.SUPPRESS, 'F') = 'F')
    WHERE JC.ROLLYEAR = JA.ROLLYEAR 
        AND JC.JA000_OID = JA.JA000_OID 
        AND NVL(JC.SUPPRESS, 'F') = 'F'          
        AND JCC.OCCUPANCY_NUM NOT IN 
('556','740','745','790','791','797','805','810','850','851','900','901','902','903','904','905','910','920','921','922','923','924','925','926','927','928','930','931','999','1814','1818','1820')                                                              
--                    ('900','901','902','903','904','905','910','920','921','922','923','924','925','926','927','928','930','931','810') /*LANDCOR COM EXTRACT*/                   
        ),0) AS GROSS_BUILDING_AREA
          
    ,NULL AS GROSS_LEASABLE_AREA
	,NULL AS NET_LEASABLE_AREA            
                          
FROM DATASET DM          
	JOIN BCA_AO.LINK_JA000_OA000 JAOA
    	ON (JAOA.ROLLYEAR = DM.ROLLYEAR AND JAOA.OA000_OID = DM.OA000_OID)
    JOIN BCA_AO.JA000_COMBUILDING JA
    	ON (JA.ROLLYEAR = JAOA.ROLLYEAR AND JA.JA000_OID = JAOA.JA000_OID)   
    	
WHERE EXISTS (
        SELECT 'X'
        FROM BCA_AO.OA000_PROPERTY OA
        WHERE OA.ROLLYEAR = DM.ROLLYEAR
            AND OA.OA000_OID = DM.OA000_OID
            AND OA.VALUE_METHOD_CALC = 'CST' 
	)

ORDER BY 3,4,5